const CONFIG = window.POLLA_CONFIG || {};
const countryFlags = {"Argentina":"🇦🇷","Australia":"🇦🇺","Bélgica":"🇧🇪","Belgica":"🇧🇪","Brasil":"🇧🇷","Canadá":"🇨🇦","Canada":"🇨🇦","Colombia":"🇨🇴","Egipto":"🇪🇬","España":"🇪🇸","Espana":"🇪🇸","Estados Unidos":"🇺🇸","Francia":"🇫🇷","Inglaterra":"🏴","Marruecos":"🇲🇦","México":"🇲🇽","Mexico":"🇲🇽","Noruega":"🇳🇴","Paraguay":"🇵🇾","Portugal":"🇵🇹","Suiza":"🇨🇭","Ghana":"🇬🇭"};
const normalize = v => String(v ?? "").replace(/\uFEFF/g,"").replace(/[\n\r]/g," ").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
const compact = v => normalize(v).replace(/[^a-z0-9]/g,"");
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>String(v).trim()!==""))rows.push(row);return rows}
function rowsToObjects(raw, required=[]){if(!raw.length)return[];let hi=0;if(required.length){hi=raw.findIndex(r=>{const nr=r.map(compact);return required.every(h=>nr.includes(compact(h)))});if(hi<0)hi=raw.findIndex(r=>r.some(c=>required.map(compact).includes(compact(c))))}if(hi<0)hi=0;const headers=raw[hi].map(h=>String(h).replace(/\n/g," ").trim());return raw.slice(hi+1).map(r=>{const o={};headers.forEach((h,i)=>o[h]=String(r[i]??"").trim());return o}).filter(o=>Object.values(o).some(v=>String(v).trim()!==""))}
function get(row, aliases){const keys=Object.keys(row||{});for(const a of aliases){const k=keys.find(k=>compact(k)===compact(a));if(k)return row[k]}for(const a of aliases){const k=keys.find(k=>compact(k).includes(compact(a))||compact(a).includes(compact(k)));if(k)return row[k]}return""}
function num(v){if(v===null||v===undefined||v==="")return 0;const n=Number(String(v).replace(",","."));return Number.isFinite(n)?n:0}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function withFlag(team){const clean=String(team||"").trim();if(!clean)return"Por definir";return `${countryFlags[clean]||""} ${esc(clean)}`.trim()}
async function fetchSheet(url,label,req){if(!url)return[];const res=await fetch(url,{cache:"no-store"});if(!res.ok)throw new Error(`No se pudo cargar ${label}`);return rowsToObjects(parseCSV(await res.text()),req)}
function setText(id,t){const el=document.getElementById(id);if(el)el.textContent=t}
let rankingRows=[],resultsRows=[],scoresRows=[],bonusRows=[];
function prepareRanking(rows){const filtered=rows.filter(r=>get(r,["Participante","Nombre"]));const sorted=filtered.sort((a,b)=>num(get(b,["Total"]))-num(get(a,["Total"]))||get(a,["Participante"]).localeCompare(get(b,["Participante"])));const totals=[...new Set(sorted.map(r=>num(get(r,["Total"]))))].sort((a,b)=>b-a);return sorted.map(r=>({...r,_rank:totals.indexOf(num(get(r,["Total"])))+1}))}
function renderPodium(rows){const top=rows.filter(r=>r._rank<=3).slice(0,3),medals={1:"🥇",2:"🥈",3:"🥉"};document.getElementById("podiumGrid").innerHTML=top.map(r=>`<article class="podium-card"><div class="medal">${medals[r._rank]||"🏅"}</div><strong>${esc(get(r,["Participante"]))}</strong><small>Puesto ${r._rank} · ${num(get(r,["Total"]))} pts</small><small>Octavos: ${num(get(r,["Octavos"]))} · Cuartos: ${num(get(r,["Cuartos"]))}</small></article>`).join("")}
function renderRanking(rows){const prepared=prepareRanking(rows),tbody=document.querySelector("#rankingTable tbody"),select=document.getElementById("participantSelect");tbody.innerHTML="";select.innerHTML='<option value="">Selecciona un participante</option>';prepared.forEach(r=>{const p=get(r,["Participante"]),cls=r._rank===1?"top":r._rank===2?"second":r._rank===3?"third":"";const tr=document.createElement("tr");tr.innerHTML=`<td><span class="rank ${cls}">${r._rank}</span></td><td>${esc(p)}</td><td class="num">${num(get(r,["Octavos"]))}</td><td class="num">${num(get(r,["Cuartos"]))}</td><td class="num">${num(get(r,["Semifinal"]))}</td><td class="num">${num(get(r,["3er y 4to puesto","3er y 4to"]))}</td><td class="num">${num(get(r,["Final"]))}</td><td class="num">${num(get(r,["Bonus"]))}</td><td class="num total">${num(get(r,["Total"]))}</td>`;tr.onclick=()=>{select.value=p;renderParticipantDetail(p);document.querySelector("#participantDetail").scrollIntoView({behavior:"smooth",block:"center"})};tbody.appendChild(tr);const opt=document.createElement("option");opt.value=p;opt.textContent=p;select.appendChild(opt)});const leader=prepared[0];setText("leaderName",leader?get(leader,["Participante"]):"-");setText("leaderPts",leader?`${num(get(leader,["Total"]))} pts`:"- pts");setText("participantCount",prepared.length);renderPodium(prepared)}
function renderResults(rows){const tbody=document.querySelector("#resultsTable tbody");tbody.innerHTML="";const filtered=rows.filter(r=>num(get(r,["Orden"]))>0&&num(get(r,["Orden"]))<=16).sort((a,b)=>num(get(a,["Orden"]))-num(get(b,["Orden"])));let played=0,next=null;filtered.forEach(r=>{const orden=num(get(r,["Orden"])),ronda=get(r,["Ronda"]),a=get(r,["Equipo A Real","Equipo A","Local"]),b=get(r,["Equipo B Real","Equipo B","Visitante"]),ga=get(r,["Goles A Real","Goles A"]),gb=get(r,["Goles B Real","Goles B"]),marc=get(r,["Marcador real","Marcador"])||(ga!==""&&gb!==""?`${ga}-${gb}`:""),clas=get(r,["Clasificado real","Clasificado"]),estado=get(r,["Estado"])||(marc?"Completo":"Pendiente"),complete=normalize(estado).includes("completo")||(ga!==""&&gb!==""&&clas);if(complete)played++;if(!complete&&!next&&a&&b)next={a,b,ronda};const tr=document.createElement("tr");tr.innerHTML=`<td>${orden}</td><td>${esc(ronda)}</td><td class="match">${withFlag(a)} vs ${withFlag(b)}</td><td>${esc(marc||"-")}</td><td>${clas?withFlag(clas):"-"}</td><td><span class="status ${complete?"complete":"pending"}">${complete?"Completo":"Pendiente"}</span></td>`;tbody.appendChild(tr)});setText("playedCount",played);setText("totalMatches",`de ${filtered.length||16} partidos`);setText("nextMatch",next?`${next.a} vs ${next.b}`:"-");setText("nextRound",next?next.ronda:"Sin próximos definidos")}
function renderParticipantDetail(p){const c=document.getElementById("participantDetail");if(!p){c.className="detail-empty";c.innerHTML="Selecciona un participante para ver el detalle.";return}const rows=scoresRows.filter(r=>normalize(get(r,["Participante"]))===normalize(p)).filter(r=>num(get(r,["Orden","Ord en"]))>0&&num(get(r,["Orden","Ord en"]))<=16).sort((a,b)=>num(get(a,["Orden","Ord en"]))-num(get(b,["Orden","Ord en"])));if(!rows.length){c.className="detail-empty";c.innerHTML="No hay puntajes detallados para este participante.";return}c.className="";c.innerHTML=rows.map(r=>{const orden=num(get(r,["Orden","Ord en"])),ronda=get(r,["Ronda"]),llave=get(r,["Llave"]),ap=get(r,["Equipo A Pron.","Equipo A Pron"]),bp=get(r,["Equipo B Pron.","Equipo B Pron"]),gap=get(r,["Goles A Pron.","Goles A Pron"]),gbp=get(r,["Goles B Pron.","Goles B Pron"]),cp=get(r,["Clasificado Pron.","Clasificado Pron"]),ar=get(r,["Equipo A Real"]),br=get(r,["Equipo B Real"]),total=num(get(r,["Total Partido","Total"]));return `<div class="detail-card"><strong><span>${orden}. ${esc(ronda)} · ${esc(llave)}</span><span class="badge">${total} pts</span></strong><div>Pronóstico: ${withFlag(ap)} ${esc(gap||"-")} - ${esc(gbp||"-")} ${withFlag(bp)}</div><div class="detail-meta">Clasificado pronosticado: ${cp?withFlag(cp):"-"}</div><div class="detail-meta">Real: ${withFlag(ar)} vs ${withFlag(br)}</div><div class="detail-meta">Resultado: ${num(get(r,["Pts Resultado"]))} · Goles: ${num(get(r,["Pts Goles"]))} · Marcador: ${num(get(r,["Pts Marcador"]))}</div></div>`}).join("")}
function renderBonus(rows){const tbody=document.querySelector("#bonusTable tbody");tbody.innerHTML="";rows.filter(r=>get(r,["Participante"])).forEach(r=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(get(r,["Participante"]))}</td><td>${withFlag(get(r,["Campeón Pron.","Campeón","Campeon Pron."]))}</td><td>${withFlag(get(r,["Subcampeón Pron.","Subcampeón","Subcampeon Pron."]))}</td><td>${withFlag(get(r,["3er Puesto Pron.","3er Puesto"]))}</td><td>${withFlag(get(r,["4to Puesto Pron.","4to Puesto"]))}</td><td>${esc(get(r,["Goleador Pron.","Goleador"]))}</td><td class="num total">${num(get(r,["Total Bonus"]))}</td>`;tbody.appendChild(tr)})}
function renderStats(){const stats=[];const ranking=prepareRanking(rankingRows);if(ranking.length){const topOct=[...ranking].sort((a,b)=>num(get(b,["Octavos"])-num(get(a,["Octavos"]))))[0];stats.push(["Más puntos en octavos",`${get(topOct,["Participante"])} · ${num(get(topOct,["Octavos"]))} pts`])}const exact={},result={};scoresRows.forEach(r=>{const p=get(r,["Participante"]);if(!p)return;if(num(get(r,["Pts Marcador"]))>0)exact[p]=(exact[p]||0)+1;if(num(get(r,["Pts Resultado"]))>0)result[p]=(result[p]||0)+1});const te=Object.entries(exact).sort((a,b)=>b[1]-a[1])[0],tr=Object.entries(result).sort((a,b)=>b[1]-a[1])[0];stats.push(["Marcadores exactos",te?`${te[0]} · ${te[1]}`:"Aún sin datos"]);stats.push(["Resultados acertados",tr?`${tr[0]} · ${tr[1]}`:"Aún sin datos"]);stats.push(["Avance del torneo",`${resultsRows.filter(r=>normalize(get(r,["Estado"])).includes("completo")).length} partidos completos`]);document.getElementById("statsGrid").innerHTML=stats.map(([t,v])=>`<div class="stat-item"><strong>${esc(t)}</strong><span>${esc(v)}</span></div>`).join("")}
function setup(){document.getElementById("searchInput").addEventListener("input",e=>renderRanking(rankingRows.filter(r=>normalize(get(r,["Participante"])).includes(normalize(e.target.value)))));document.getElementById("participantSelect").addEventListener("change",e=>renderParticipantDetail(e.target.value))}
function showError(e){document.querySelector("main").innerHTML=`<div class="error"><strong>Error cargando el dashboard.</strong><br>${esc(e.message)}<br><br>Revisa los links CSV en config.js.</div>`}
async function init(){try{document.title=CONFIG.title||"Polla Familiar Mundial 2026";[rankingRows,resultsRows,scoresRows,bonusRows]=await Promise.all([fetchSheet(CONFIG.rankingCsvUrl,"Ranking",["Participante","Total"]),fetchSheet(CONFIG.resultsCsvUrl,"Resultados",["Orden","Ronda"]),fetchSheet(CONFIG.scoresCsvUrl,"Puntajes",["Participante","Ronda"]),fetchSheet(CONFIG.bonusCsvUrl,"Puntajes Bonus",["Participante"])]);renderRanking(rankingRows);renderResults(resultsRows);renderBonus(bonusRows);renderStats();setup();setText("lastUpdated",new Date().toLocaleString("es-PE",{dateStyle:"medium",timeStyle:"short"}))}catch(e){showError(e)}}
init();
